config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  resources :users
  resources :products do
    resources :comments
  end
  
  get 'static_pages/about'

  get 'static_pages/contact'
  post 'static_pages/thank_you'

  get 'static_pages/index'

  post 'payments/create'
  get 'payments/create'
  
  mount ActionCable.server => '/cable'
 
 
  root 'static_pages#landing_page'

  resources :orders, only: [:index, :show, :create, :destroy]

  get 'static_pages/landing_page'

  #devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Julinsecommerce</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
     <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link href="https://fonts.googleapis.com/css?family=Acme" rel="stylesheet">

   <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
   <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  <!--script src="js/jquery.stellar.min.js"></script-->

   <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
  </head>

  <body>
  
  <!--flash messages für mailer-->
    
    <div class="row">
      <% if alert %>
        <p class="alert alert-notice" role="alert"><%= alert %></p>
      <% end %>

      <% if notice %>
        <p  id="notice" class="alert alert-info" role="alert"><%= notice %></p>
      <% end %>
     </div>

    
   

   <!--p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p-->

    <!--navbar starts here-->
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>          
          <div class="projectName navbar-brand">
            <%= image_tag("hibiskusgezeichnet.png", class: "img-responsive hoian") %>        
          </div> <!--end projectName -->          
        </div> <!--end navbar-header -->  

        <div class="navbar-collapse collapse">
        
          <ul class="navbar-right nav navbar-nav" id=mynavbar>
            <li class="active"> <%= link_to 'Home', root_path %> </li> 
            <li class="active"> <%= link_to 'Vacation!', products_path %> </li> 
            <li class="active"> <%= link_to 'About', static_pages_index_path %> </li> 
            <li class="active"> <%= link_to 'Contact', static_pages_contact_path %> </li>
            
<!--hier war der Search-Knopf-->

          </ul>

          <ul class="nav pull-right">
            <li>
                <% if user_signed_in? %>
                  <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'btn btn-primary') %>
                <% else %>
                  <%= link_to('Login', new_user_session_path, class: 'btn btn-primary', id: 'login', style: 'font-size: 1.3em') %>
                <% end %>
            </li>
          </ul>

        </div>
      </div> <!-- end nav container--> 
    </nav>

    <%= yield %>
   

    <footer>
       &copy; 2017 Julin
       <p> <span class="glyphicon glyphicon-arrow-up"></span> 
       <a href=#> Back to top </a>  
    </footer>

  </body>

</html>